# -*- coding: utf-8 -*-
"""Copy of FogTest_neural

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmwtlc667UW38N-EOA8ZFFgLtw8Z6o91
"""

#@title Import relevant modules
#!pip install scikeras
!pip install imbalanced-learn
!pip install dask
#from scikeras.wrappers import KerasClassifier
import numpy as np
import pandas as pd
import tensorflow as tf
from collections import Counter
from tensorflow import keras
from sklearn.preprocessing import StandardScaler, LabelEncoder
from keras.utils import to_categorical
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout, Bidirectional, GRU, BatchNormalization, LeakyReLU, PReLU, ELU, ReLU, Input
from tensorflow.keras.activations import tanh
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout, Flatten, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.metrics import Precision, Recall, Accuracy, AUC
from tensorflow.keras.initializers import Constant
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import resample
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import BorderlineSMOTE, SMOTE
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import dask.dataframe as dd

# The following lines adjust the granularity of reporting.
pd.options.display.max_rows = 10
pd.options.display.float_format = "{:.1f}".format

print("Imported modules.")

"""# Binary Classification

"""

# @title Cleaning the Data
# Load the CSV file into a DataFrame
# Define the path and pattern for the CSV files
path = 'Era5_Yarmouth_1KM.csv'

# Compute the Dask DataFrame to get a Pandas DataFrame
combined_df = pd.read_csv(path)
# Remove rows where the first column is blank
df_cleaned = combined_df[combined_df['Vis'].notnull()]

# Save the cleaned DataFrame back to a CSV file
df_cleaned.to_csv('cleaned_file.csv', index=False)

# @title Data Preparation
# Convert 'Time' column to datetime with the correct format
data = df_cleaned.copy()
data['Time'] = pd.to_datetime(data['Time'], format='%Y-%m-%d_%H:%M:%S', errors='coerce')

# Extract time-based features
data['Hour'] = data['Time'].dt.hour
data['Day'] = data['Time'].dt.day
data['Month'] = data['Time'].dt.month
data['DayOfWeek'] = data['Time'].dt.dayofweek

# Sort the data by time
data = data.sort_values(by='Time')

data = data[data['Month'] > 3]

# Binary classification: Map 'class_vis' to binary classes
data['class_vis'] = data['class_vis'].map({'clear': 0, 'fog': 1})

# Create lag features
lag_features = ['T2','U','V','RH2','P_sfc']  # Replace with your actual feature names
for feature in lag_features:
    for lag in range(1, 2):  # Creating lag features for the past 2 time steps
        data[f'{feature}_lag_{lag}'] = data[feature].shift(lag)

# Drop rows with missing values created by lag features
data = data.dropna()

# Split data into features and target
X = data.drop(['Time', 'class_vis', 'Vis','T2-TD2','TD2'], axis=1)  # Dropping 'Time' as it is now decomposed into useful features
y = data['class_vis']

# Train-test split based on time
train_size = int(len(data) * 0.9)

X_train1, X_test = X[:train_size], X[train_size:]
y_train1, y_test = y[:train_size], y[train_size:]

# Calculate the split index
split_index = int(len(X_train1) * 0.8)

# Create training and validation sets
X_train, X_val = X_train1[:split_index], X_train1[split_index:]
y_train, y_val = y_train1[:split_index], y_train1[split_index:]

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)
X_val_scaled = scaler.fit_transform(X_val)

# Apply SMOTE for data balancing
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import BorderlineSMOTE
smote = SMOTEENN()
#X_train_scaled, y_train = smote.fit_resample(X_train_scaled, y_train)
#X_val_scaled, y_val = smote.fit_resample(X_val_scaled, y_val)
# Reshape data for LSTM
X_train_resampled = X_train_scaled.reshape((X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_test_resampled = X_test_scaled.reshape((X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))
X_val_resampled = X_val_scaled.reshape((X_val_scaled.shape[0], 1, X_val_scaled.shape[1]))

# Define class labels (0 and 1 for binary classification)
class_labels = np.unique(y_train)

# Compute class weights
class_weights = compute_class_weight(class_weight="balanced", classes=class_labels, y=y_train)

# Convert to dictionary format
class_weights_dict = {i: weight for i, weight in enumerate(class_weights)}

from sklearn.utils.class_weight import compute_sample_weight

# Compute sample weights
sample_weights = compute_sample_weight(class_weight='balanced', y=y_train)
print(class_weights_dict)
print(sample_weights)
print(X_val_scaled.shape)
print(X_train_scaled.shape)


# Setting the initial bias
pos = np.sum(y_train == 1)  # Count of positive samples
neg = np.sum(y_train == 0)  # Count of negative samples

#initial_bias = np.log([pos / neg])
initial_bias = 0
print(initial_bias)

# @title Building the Model St John's

from tensorflow.keras.optimizers import RMSprop, Nadam

# Define custom F1 Score metric
class F1Score(tf.keras.metrics.Metric):
    def __init__(self, name="f1_score", **kwargs):
        super(F1Score, self).__init__(name=name, **kwargs)
        self.precision = Precision()
        self.recall = Recall()

    def update_state(self, y_true, y_pred, sample_weight=None):
        self.precision.update_state(y_true, y_pred, sample_weight)
        self.recall.update_state(y_true, y_pred, sample_weight)

    def result(self):
        p = self.precision.result()
        r = self.recall.result()
        return 2 * (p * r) / (p + r + tf.keras.backend.epsilon())

    def reset_state(self):
        self.precision.reset_state()
        self.recall.reset_state()

# List of metrics including custom F1 score
METRICS = [
    keras.metrics.BinaryCrossentropy(name='cross_entropy'),
    keras.metrics.MeanSquaredError(name='Brier_score'),
    keras.metrics.TruePositives(name='tp'),
    keras.metrics.FalsePositives(name='fp'),
    keras.metrics.TrueNegatives(name='tn'),
    keras.metrics.FalseNegatives(name='fn'),
    keras.metrics.BinaryAccuracy(name='accuracy'),
    keras.metrics.Precision(name='precision'),
    keras.metrics.Recall(name='recall'),
    keras.metrics.AUC(name='auc'),
    keras.metrics.AUC(name='prc', curve='PR'),  # Precision-recall curve
    F1Score()
]



# Define LSTM layers
model = Sequential([
    Input(shape=(X_train_resampled.shape[1], X_train_resampled.shape[2])),  # Input shape

    # First LSTM Layer
    Bidirectional(LSTM(32, activation='tanh', return_sequences=True)),  # tanh is default lstm
    BatchNormalization(),
    Dropout(0.2),

    # Second LSTM Layer
    Bidirectional(LSTM(32, activation='tanh', return_sequences=False)),
    BatchNormalization(),
    Dropout(0.2),

    # Fully Connected Layers
    Dense(16, activation=None),  # No activation, since we use LeakyReLU
    LeakyReLU(negative_slope=0.01),
    BatchNormalization(),
    Dropout(0.2),

    Dense(16, activation=None),
    LeakyReLU(negative_slope=0.01),
    BatchNormalization(),

    Dropout(0.2),

    # Output Layer
    Dense(1, activation='sigmoid', bias_initializer=Constant(initial_bias))  # Binary classification
])

# Set the initial learning rate
learning_rate = 0.0001
optimizer = Adam(learning_rate=learning_rate)
#optimizer = RMSprop(learning_rate=learning_rate, rho=0.9, epsilon=1e-06)
#optimizer = Nadam(learning_rate=learning_rate)
# Compile the model
model.compile(optimizer= optimizer, loss='binary_crossentropy', metrics= METRICS) # [Precision(), Recall(),F1Score() ]

# Train the model
early_stopping = EarlyStopping(monitor='val_f1_score', patience=20, restore_best_weights=True, mode='max')
reduce_lr = ReduceLROnPlateau(monitor='val_f1_score', factor=0.5, patience=5, min_lr=1e-7, mode='max')

history = model.fit(X_train_resampled, y_train, epochs=200, batch_size= 128, validation_data= (X_val_resampled, y_val), callbacks=[early_stopping, reduce_lr], class_weight= class_weights_dict)  #, sample_weight = sample_weights

# Save the model
#model.save('lstm_onebinary.keras')

# Plotting the results
plt.figure(figsize=(14, 6))

# Accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['f1_score'], label='F1Score')
plt.plot(history.history['val_f1_score'], label='val_F1Score')
plt.xlabel('Epoch')
plt.ylabel('F1Score')
plt.legend()
plt.title('(a) Model F1-Score over Epochs')

# Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('(b) Model Loss over Epochs')
plt.suptitle("LSTM Model Performance for St John's", fontsize=16)
plt.show()

# amount of parameters
model.summary()

# @title Visualizing the Performance
# Evaluate the model
y_pred = model.predict(X_test_resampled)
y_pred = y_pred.reshape(-1)
y_pred_classes = (y_pred > 0.82).astype("int32")

# Classification report
print("Classification Report:")
print(classification_report(y_test, y_pred_classes))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for St Johns')
plt.show()

"""## Yarmouth"""

# @title Building the model for Yarmouth
# Define LSTM layers
model = Sequential([
    Input(shape=(X_train_resampled.shape[1], X_train_resampled.shape[2])),  # Input shape

    # First LSTM Layer
    Bidirectional(LSTM(16, activation='tanh', return_sequences=True)),  # tanh is default lstm
    BatchNormalization(),
    Dropout(0.2),

    # Second LSTM Layer
    Bidirectional(LSTM(16, activation='tanh', return_sequences=False)),
    BatchNormalization(),
    Dropout(0.2),

    # Fully Connected Layers
    Dense(8, activation=None),  # No activation, since we use LeakyReLU
    LeakyReLU(negative_slope=0.01),
    BatchNormalization(),
    Dropout(0.2),

    Dense(8, activation=None),
    LeakyReLU(negative_slope=0.01),
    BatchNormalization(),

    Dropout(0.2),

    # Output Layer
    Dense(1, activation='sigmoid', bias_initializer=Constant(initial_bias))  # Binary classification
])

# Set the initial learning rate
learning_rate = 0.0001
optimizer = Adam(learning_rate=learning_rate)
#optimizer = RMSprop(learning_rate=learning_rate, rho=0.9, epsilon=1e-06)
#optimizer = Nadam(learning_rate=learning_rate)
# Compile the model
model.compile(optimizer= optimizer, loss='binary_crossentropy', metrics= METRICS) # [Precision(), Recall(),F1Score() ]

# Train the model
early_stopping = EarlyStopping(monitor='val_f1_score', patience=20, restore_best_weights=True, mode='max')
reduce_lr = ReduceLROnPlateau(monitor='val_f1_score', factor=0.5, patience=5, min_lr=1e-7, mode='max')

history = model.fit(X_train_resampled, y_train, epochs=200, batch_size= 128, validation_data= (X_val_resampled, y_val), callbacks=[early_stopping, reduce_lr], class_weight= class_weights_dict)  #, sample_weight = sample_weights

# Save the model
#model.save('lstm_onebinary.keras')

# Plotting the results
plt.figure(figsize=(14, 6))

# Accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['f1_score'], label='F1Score')
plt.plot(history.history['val_f1_score'], label='val_F1Score')
plt.xlabel('Epoch')
plt.ylabel('F1Score')
plt.legend()
plt.title('(a) Model F1-Score over Epochs')

# Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('(b) Model Loss over Epochs')
plt.suptitle('LSTM Model Performance for Yarmouth', fontsize=16)
plt.show()

# amount of parameters
model.summary()

# @title Visualizing the Performance for Yarmouth
# Evaluate the model
y_pred = model.predict(X_test_resampled)
y_pred = y_pred.reshape(-1)
y_pred_classes = (y_pred > 0.75).astype("int32")

# Classification report
print("Classification Report:")
print(classification_report(y_test, y_pred_classes))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for Yarmouth(LSTM)')
plt.show()

# @title New data (St John's)
# Define the path and pattern for the CSV files
path = 'testStjohn2024_1KM.csv'

# Compute the Dask DataFrame to get a Pandas DataFrame
combined_df = pd.read_csv(path)
# Remove rows where the first column is blank
df_cleaned1 = combined_df[combined_df['Vis'].notnull()]

# Save the cleaned DataFrame back to a CSV file
df_cleaned1.to_csv('cleaned1_file.csv', index=False)

# @title Data Preparation
# Convert 'Time' column to datetime with the correct format
data1 = df_cleaned1.copy()
data1['Time'] = pd.to_datetime(data1['Time'], format='%Y-%m-%d_%H:%M:%S', errors='coerce')

# Extract time-based features
data1['Hour'] = data1['Time'].dt.hour
data1['Day'] = data1['Time'].dt.day
data1['Month'] = data1['Time'].dt.month
data1['DayOfWeek'] = data1['Time'].dt.dayofweek

# Sort the data by time
data1 = data1.sort_values(by='Time')

data1 = data1[data1['Month'] > 3]

# Binary classification: Map 'class_vis' to binary classes
data1['class_vis'] = data1['class_vis'].map({'clear': 0, 'fog': 1})

# Create lag features
lag_features = ['T2','U','V','RH2','P_sfc']  # Replace with your actual feature names
for feature in lag_features:
    for lag in range(1, 2):  # Creating lag features for the past 2 time steps
        data1[f'{feature}_lag_{lag}'] = data1[feature].shift(lag)

# Drop rows with missing values created by lag features
data1 = data1.dropna()

# Split data into features and target
X1 = data1.drop(['Time', 'class_vis', 'Vis'], axis=1)  # Dropping 'Time' as it is now decomposed into useful features
y_new = data1['class_vis']

# Standardize the features
X_new_scaled = scaler.fit_transform(X1)

# Reshape data for LSTM
X_new_resampled = X_new_scaled.reshape((X_new_scaled.shape[0], 1, X_new_scaled.shape[1]))

# Evaluate the model
y_new_pred = model.predict(X_new_resampled)
y_new_pred = y_new_pred.reshape(-1)
y_new_pred_classes = (y_new_pred > 0.85).astype("int32")

# Classification report
print("Classification Report:")
print(classification_report(y_new, y_new_pred_classes))

# Confusion matrix
cm = confusion_matrix(y_new, y_new_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for St Johns 2024(LSTM)')
plt.show()

# @title New data (Yarmouth)
# Define the path and pattern for the CSV files
path = 'testYarmouth2024_1KM.csv'

# Compute the Dask DataFrame to get a Pandas DataFrame
combined_df = pd.read_csv(path)
# Remove rows where the first column is blank
df_cleaned1 = combined_df[combined_df['Vis'].notnull()]

# Save the cleaned DataFrame back to a CSV file
df_cleaned1.to_csv('cleaned1_file.csv', index=False)

# @title Data Preparation
# Convert 'Time' column to datetime with the correct format
data1 = df_cleaned1.copy()
data1['Time'] = pd.to_datetime(data1['Time'], format='%Y-%m-%d_%H:%M:%S', errors='coerce')

# Extract time-based features
data1['Hour'] = data1['Time'].dt.hour
data1['Day'] = data1['Time'].dt.day
data1['Month'] = data1['Time'].dt.month
data1['DayOfWeek'] = data1['Time'].dt.dayofweek

# Sort the data by time
data1 = data1.sort_values(by='Time')

data1 = data1[data1['Month'] > 3]

# Binary classification: Map 'class_vis' to binary classes
data1['class_vis'] = data1['class_vis'].map({'clear': 0, 'fog': 1})

# Create lag features
lag_features = ['T2','U','V','RH2','P_sfc']  # Replace with your actual feature names
for feature in lag_features:
    for lag in range(1, 2):  # Creating lag features for the past 2 time steps
        data1[f'{feature}_lag_{lag}'] = data1[feature].shift(lag)

# Drop rows with missing values created by lag features
data1 = data1.dropna()

# Split data into features and target
X1 = data1.drop(['Time', 'class_vis', 'Vis'], axis=1)  # Dropping 'Time' as it is now decomposed into useful features
y_new = data1['class_vis']

# Standardize the features
X_new_scaled = scaler.fit_transform(X1)

# Reshape data for LSTM
X_new_resampled = X_new_scaled.reshape((X_new_scaled.shape[0], 1, X_new_scaled.shape[1]))

# Evaluate the model
y_new_pred = model.predict(X_new_resampled)
y_new_pred = y_new_pred.reshape(-1)
y_new_pred_classes = (y_new_pred > 0.75).astype("int32")

# Classification report
print("Classification Report:")
print(classification_report(y_new, y_new_pred_classes))

# Confusion matrix
cm = confusion_matrix(y_new, y_new_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix for Yarmouth 2024(LSTM)')
plt.show()