# -*- coding: utf-8 -*-
"""Copy of FogTest_Decisiontree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VucQJJFmURrn1iShFHWBFZhnfXiQL4sH
"""

# Commented out IPython magic to ensure Python compatibility.
#@title Import relevant modules
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import BorderlineSMOTE, SMOTE
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, ExtraTreesRegressor
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,  make_scorer,confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import dask.dataframe as dd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import warnings, gc, joblib
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score, KFold, GridSearchCV, RepeatedKFold, TimeSeriesSplit
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, ConfusionMatrixDisplay, accuracy_score, precision_score, recall_score, f1_score
from scipy.stats import probplot, randint
from imblearn.over_sampling import BorderlineSMOTE

# The following lines adjust the granularity of reporting.
pd.options.display.max_rows = 10
pd.options.display.float_format = "{:.1f}".format

print("Imported modules.")

"""# Binary Classification

## One location
"""

# @title Cleaning the Data
# Load the CSV file into a DataFrame
# Define the path and pattern for the CSV files
path = 'Era5_Yarmouth_1KM.csv'

# Compute the Dask DataFrame to get a Pandas DataFrame
combined_df = pd.read_csv(path)
# Remove rows where the first column is blank
df_cleaned = combined_df[combined_df['Vis'].notnull()]

# Save the cleaned DataFrame back to a CSV file
df_cleaned.to_csv('cleaned_file.csv', index=False)

# @title Data Preparation
# Convert 'Time' column to datetime with the correct format
data = df_cleaned.copy()
data['Time'] = pd.to_datetime(data['Time'], format='%Y-%m-%d_%H:%M:%S', errors='coerce')

# Extract time-based features
data['Hour'] = data['Time'].dt.hour
#data['Day'] = data['Time'].dt.day
data['Month'] = data['Time'].dt.month
#data['sin_hour'] = np.sin(2 * np.pi * data['Hour'] / 24)
#df['cos_hour'] = np.cos(2 * np.pi * data['hour'] / 24)
# Sort the data by time
data = data.sort_values(by='Time')

data = data[data['Month'] > 3]

# Binary classification: Map 'class_vis' to binary classes
data['class_vis'] = data['class_vis'].map({'clear': 0, 'fog': 1})

# Create lag features
lag_features = ['T2','U','V','RH2','P_sfc']  # Replace with your actual feature names
for feature in lag_features:
     for lag in range(1, 2):  # Creating lag features for the past 2 time steps
         data[f'{feature}_lag_{lag}'] = data[feature].shift(lag)

# Define the frequency of your data
lag_hours = 1

# Create a lagged feature for 'class_vis'
#data['class_vis_lag_24hr'] = data['Vis'].shift(lag_hours)

# Drop rows with missing values created by lag features
data = data.dropna()

# Split data into features and target
X = data.drop(['Time', 'class_vis', 'Vis','T2-TD2','TD2'], axis=1)  # Dropping 'Time' as it is now decomposed into useful features
y = data['class_vis']

# Train-test split based on time
train_size = int(len(data) * 0.9)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Apply SMOTE for data balancing
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import BorderlineSMOTE
smote = SMOTEENN()
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)

# @title Find the parameters for St John

# Define the parameter distribution for RandomizedSearchCV
param_dist = {
    'n_estimators': randint(100, 500),
    'criterion': ['gini', 'log_loss', 'entropy'],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [10, 20, 30, 40, None],
    'min_samples_split': randint(2, 15),
    'min_samples_leaf': randint(1, 5),
    'class_weight': ['balanced', 'balanced_subsample'],
    'bootstrap': [True, False]
}

# Initialize the Extra Trees classifier
et_classifier = ExtraTreesClassifier()

# Initialize RandomizedSearchCV
#random_search = RandomizedSearchCV(estimator=et_classifier, param_distributions=param_dist, scoring= f1_score, n_iter=50, cv=5, n_jobs=-1, verbose=2)

# Define the TimeSeriesSplit cross-validator
tscv = TimeSeriesSplit(n_splits=5)
random_search = RandomizedSearchCV(estimator=et_classifier, param_distributions=param_dist, scoring= make_scorer(f1_score, average='weighted'), n_iter=50, cv=tscv, n_jobs=-1, verbose=2)

# Fit the model
random_search.fit(X_train_res, y_train_res)

# Print the best parameters
print("Best Parameters:", random_search.best_params_)

# @title Find the parameters for St John with lagged Vis

# Define the parameter distribution for RandomizedSearchCV
param_dist = {
    'n_estimators': randint(100, 500),
    'criterion': ['gini', 'log_loss', 'entropy'],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [10, 20, 30, 40, None],
    'min_samples_split': randint(2, 15),
    'min_samples_leaf': randint(1, 5),
    'class_weight': ['balanced', 'balanced_subsample'],
    'bootstrap': [True, False]
}

# Initialize the Extra Trees classifier
et_classifier = ExtraTreesClassifier()

# Initialize RandomizedSearchCV
#random_search = RandomizedSearchCV(estimator=et_classifier, param_distributions=param_dist, scoring= f1_score, n_iter=50, cv=5, n_jobs=-1, verbose=2)

# Define the TimeSeriesSplit cross-validator
tscv = TimeSeriesSplit(n_splits=5)
random_search = RandomizedSearchCV(estimator=et_classifier, param_distributions=param_dist, scoring= make_scorer(f1_score, average='weighted'), n_iter=50, cv=tscv, n_jobs=-1, verbose=2)

# Fit the model
random_search.fit(X_train_res, y_train_res)

# Print the best parameters
print("Best Parameters:", random_search.best_params_)

# @title Building the Model (St John's)
# Initialize and train ExtraTreeClassifier
et_classifier = ExtraTreesClassifier(
    n_estimators=105,   # Number of trees 267
    criterion = 'log_loss', # purity gini
    max_depth= None,      # Maximum depth of each tree 10
    max_features= 'sqrt',  # Number of features to consider when looking for the best split sqrt
    min_samples_split=8,  # Minimum number of samples required to split an internal node 2
    min_samples_leaf=4,   # Minimum number of samples required to be at a leaf node 1
    bootstrap= True,    # Whether bootstrap samples are used when building trees True
    class_weight='balanced', # whether to use different weights balanced
    random_state=42,
#    ccp_alpha= 0.00002
)
# Fit the model
et_classifier.fit(X_train_res, y_train_res)

# Predictions
y_train_pred = et_classifier.predict(X_train_scaled)
y_test_prob = et_classifier.predict_proba(X_test_scaled)
y_test_pred = (y_test_prob[:, 1] >= 0.8).astype(int)

# Evaluation on Training Set
train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred, average='weighted')
train_recall = recall_score(y_train, y_train_pred, average='weighted')
train_f1 = f1_score(y_train, y_train_pred, average='weighted')

print(f"Training Set Evaluation:\nAccuracy: {train_accuracy:.4f}")
print(f"Precision: {train_precision:.4f}")
print(f"Recall: {train_recall:.4f}")
print(f"F1-Score: {train_f1:.4f}")

# Evaluation on Test Set
test_accuracy = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred, average='weighted')
test_recall = recall_score(y_test, y_test_pred, average='weighted')
test_f1 = f1_score(y_test, y_test_pred, average='weighted')

print(f"Test Set Evaluation:\nAccuracy: {test_accuracy:.4f}")
print(f"Precision: {test_precision:.4f}")
print(f"Recall: {test_recall:.4f}")
print(f"F1-Score: {test_f1:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_test_pred))

# Cross-Validation
cv_scores = cross_val_score(et_classifier, X, y, cv=5)
print(f"Cross-Validation Scores: {cv_scores}")
print(f"Mean CV Accuracy: {cv_scores.mean():.4f}")

# Feature Importance
importances = et_classifier.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame(importances, index=feature_names, columns=['Importance']).sort_values('Importance', ascending=False)
print("\nFeature Importance:\n", feature_importance_df)

# Visualization of Feature Importance
plt.figure(figsize=(10, 6))
sns.barplot(x=feature_importance_df['Importance'], y=feature_importance_df.index)
plt.title("Feature Importance for St John's")
plt.show()

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_test_pred)
plt.figure(figsize=(10, 7))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
plt.title("Confusion Matrix for St John's")
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# @title Find the parameters for Yarmouth

# Define the parameter distribution for RandomizedSearchCV
param_dist = {
    'n_estimators': randint(100, 500),
    'criterion': ['gini', 'log_loss', 'entropy'],
    'max_features': ['sqrt', 'log2', None],
    'max_depth': [10, 20, 30, 40, None],
    'min_samples_split': randint(2, 15),
    'min_samples_leaf': randint(1, 5),
    'class_weight': ['balanced', 'balanced_subsample'],
    'bootstrap': [True, False]
}

# Initialize the Extra Trees classifier
et_classifier = ExtraTreesClassifier()

# Initialize RandomizedSearchCV
tscv = TimeSeriesSplit(n_splits=5)
random_search = RandomizedSearchCV(estimator=et_classifier, param_distributions=param_dist, scoring= make_scorer(f1_score, average='weighted'), n_iter=50, cv=tscv, n_jobs=-1, verbose=2)

# Fit the model
random_search.fit(X_train_res, y_train_res)

# Print the best parameters
print("Best Parameters:", random_search.best_params_)

"""Best Parameters: {'bootstrap': False, 'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_depth': 40, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 12, 'n_estimators': 476}"""

# @title Building the Model (Yarmouth)
# Initialize and train ExtraTreeClassifier
et_classifier = ExtraTreesClassifier(
    n_estimators= 125,   # Number of trees 375
    criterion = 'entropy', # criteria to split gini
    max_depth= None,      # Maximum depth of each tree 20
    max_features= None,  # Number of features to consider when looking for the best split sqrt
    min_samples_split=4,  # Minimum number of samples required to split an internal node 5
    min_samples_leaf=3,   # Minimum number of samples required to be at a leaf node 2
    bootstrap= True,    # Whether bootstrap samples are used when building trees True
    class_weight='balanced_subsample', # class weight for imbalanced adjusting balanced
    random_state=42,
)
# Fit the model
et_classifier.fit(X_train_res, y_train_res)

# Predictions
y_train_pred = et_classifier.predict(X_train_scaled)
y_test_prob = et_classifier.predict_proba(X_test_scaled)
y_test_pred = (y_test_prob[:, 1] >= 0.8).astype(int)

# Evaluation on Training Set
train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred, average='weighted')
train_recall = recall_score(y_train, y_train_pred, average='weighted')
train_f1 = f1_score(y_train, y_train_pred, average='weighted')

print(f"Training Set Evaluation:\nAccuracy: {train_accuracy:.4f}")
print(f"Precision: {train_precision:.4f}")
print(f"Recall: {train_recall:.4f}")
print(f"F1-Score: {train_f1:.4f}")

# Evaluation on Test Set
test_accuracy = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred, average='weighted')
test_recall = recall_score(y_test, y_test_pred, average='weighted')
test_f1 = f1_score(y_test, y_test_pred, average='weighted')

print(f"Test Set Evaluation:\nAccuracy: {test_accuracy:.4f}")
print(f"Precision: {test_precision:.4f}")
print(f"Recall: {test_recall:.4f}")
print(f"F1-Score: {test_f1:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_test_pred))

# Cross-Validation
cv_scores = cross_val_score(et_classifier, X, y, cv=5)
print(f"Cross-Validation Scores: {cv_scores}")
print(f"Mean CV Accuracy: {cv_scores.mean():.4f}")

# Feature Importance
importances = et_classifier.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame(importances, index=feature_names, columns=['Importance']).sort_values('Importance', ascending=False)
print("\nFeature Importance:\n", feature_importance_df)

# Visualization of Feature Importance
plt.figure(figsize=(10, 6))
sns.barplot(x=feature_importance_df['Importance'], y=feature_importance_df.index)
plt.title('Feature Importance for Yarmouth')
plt.show()

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_test_pred)
plt.figure(figsize=(10, 7))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
plt.title('Confusion Matrix for Yarmouth')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# @title Testing with new data (Yarmouth)
# Create a path and read the new data with pd
path1 = 'testYarmouth2024_1KM.csv'

read1 = pd.read_csv(path1)
# Remove any blanks
read1 = read1[read1['Vis'].notnull()]
# Save to a csv file
read1.to_csv('cleaned1_file.csv', index=False)

## Data Preparation

# Convert 'Time' column to datetime with the correct format
data1 = read1.copy()
data1['Time'] = pd.to_datetime(data1['Time'], format='%Y-%m-%d_%H:%M:%S', errors='coerce')

# Extract time-based features
data1['Hour'] = data1['Time'].dt.hour
#data1['Day'] = data1['Time'].dt.day
data1['Month'] = data1['Time'].dt.month

# Sort the data by time
data1 = data1.sort_values(by='Time')

data1 = data1[data1['Month'] > 3]

# Binary classification: Map 'class_vis' to binary classes
data1['class_vis'] = data1['class_vis'].map({'clear': 0, 'fog': 1})

# Create lag features
lag_features = ['T2','U','V','RH2','P_sfc']  # Replace with your actual feature names
for feature in lag_features:
    for lag in range(1, 2):  # Creating lag features for the past 2 time steps
        data1[f'{feature}_lag_{lag}'] = data1[feature].shift(lag)
# Define the frequency of your data
lag_hours = 1

# Create a lagged feature for 'class_vis'
#data1['class_vis_lag_24hr'] = data1['Vis'].shift(lag_hours)

# Drop rows with missing values created by lag features
data1 = data1.dropna()

# Split data into features and target
X1 = data1.drop(['Time', 'class_vis', 'Vis'], axis=1)  # Dropping 'Time' as it is now decomposed into useful features
y1 = data1['class_vis']

# Feature scaling
scaler = StandardScaler()
X_new_scaled = scaler.fit_transform(X1)

# Predictions
y_new_prob = et_classifier.predict_proba(X_new_scaled)
y_new_pred = (y_new_prob[:, 1] >= 0.55).astype(int)

## Visualizing the predictions of 2024

# Evaluation on Test Set
test_accuracy = accuracy_score(y1, y_new_pred)
test_precision = precision_score(y1, y_new_pred, average='weighted')
test_recall = recall_score(y1, y_new_pred, average='weighted')
test_f1 = f1_score(y1, y_new_pred, average='weighted')

print(f"Test Set Evaluation:\nAccuracy: {test_accuracy:.4f}")
print(f"Precision: {test_precision:.4f}")
print(f"Recall: {test_recall:.4f}")
print(f"F1-Score: {test_f1:.4f}")
print("\nClassification Report:\n", classification_report(y1, y_new_pred))

# Visualizing the Confusion Matrix
conf_matrix = confusion_matrix(y1, y_new_pred)
plt.figure(figsize=(10, 7))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
plt.title('Confusion Matrix for Yarmouth 2024 (ET)')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# --- Feature Importance Plot ---
importances = et_classifier.feature_importances_
feature_names = X1.columns

# Put into a DataFrame for sorting
feat_importances = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

# Plot
plt.figure(figsize=(10, 6))
sns.barplot(x="Importance", y="Feature", data=feat_importances)
plt.title("Feature Importance - ETClassifier (Yarmouth 2024)")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

# adding the pred values to a csv file

# Add predictions to the original dataframe
data1['Predicted_class_vis'] = y_new_pred

# Save the dataframe with predictions to a new CSV file
output_df = data1[['Time', 'Vis', 'class_vis', 'Predicted_class_vis']]
output_df.to_csv('yar2024_predictions_cleaned.csv', index=False)

# @title Testing with new data (St John's)
# Create a path and read the new data with pd
path1 = 'testStjohn2024_1KM.csv'

read1 = pd.read_csv(path1)
# Remove any blanks
read1 = read1[read1['Vis'].notnull()]
# Save to a csv file
read1.to_csv('cleaned1_file.csv', index=False)

## Data Preparation

# Convert 'Time' column to datetime with the correct format
data1 = read1.copy()
data1['Time'] = pd.to_datetime(data1['Time'], format='%Y-%m-%d_%H:%M:%S', errors='coerce')

# Extract time-based features
data1['Hour'] = data1['Time'].dt.hour
#data1['Day'] = data1['Time'].dt.day
data1['Month'] = data1['Time'].dt.month
#data1['sin_hour'] = np.sin(2 * np.pi * data1['Hour'] / 24)

# Sort the data by time
data1 = data1.sort_values(by='Time')

data1 = data1[data1['Month'] > 3]

# Binary classification: Map 'class_vis' to binary classes
data1['class_vis'] = data1['class_vis'].map({'clear': 0, 'fog': 1})

# Create lag features
lag_features = ['T2','U','V','RH2','P_sfc']  # Replace with your actual feature names
for feature in lag_features:
    for lag in range(1, 2):  # Creating lag features for the past 2 time steps
        data1[f'{feature}_lag_{lag}'] = data1[feature].shift(lag)
# Define the frequency of your data
lag_hours = 1

# Create a lagged feature for 'class_vis'
#data1['class_vis_lag_24hr'] = data1['Vis'].shift(lag_hours)

# Drop rows with missing values created by lag features
data1 = data1.dropna()

# Split data into features and target
X1 = data1.drop(['Time', 'class_vis', 'Vis'], axis=1)  # Dropping 'Time' as it is now decomposed into useful features
y1 = data1['class_vis']

# Feature scaling
scaler = StandardScaler()
X_new_scaled = scaler.fit_transform(X1)

# Predictions
y_new_prob = et_classifier.predict_proba(X_new_scaled)
y_new_pred = (y_new_prob[:, 1] >= 0.65).astype(int)

## Visualizing the predictions of 2024

# Evaluation on Test Set
test_accuracy = accuracy_score(y1, y_new_pred)
test_precision = precision_score(y1, y_new_pred, average='weighted')
test_recall = recall_score(y1, y_new_pred, average='weighted')
test_f1 = f1_score(y1, y_new_pred, average='weighted')

print(f"Test Set Evaluation:\nAccuracy: {test_accuracy:.4f}")
print(f"Precision: {test_precision:.4f}")
print(f"Recall: {test_recall:.4f}")
print(f"F1-Score: {test_f1:.4f}")
print("\nClassification Report:\n", classification_report(y1, y_new_pred))

# Visualizing the Confusion Matrix
conf_matrix = confusion_matrix(y1, y_new_pred)
plt.figure(figsize=(10, 7))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
plt.title("Confusion Matrix for St John's 2024")
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

"""## All locations"""

# @title Cleaning the Data
# Load the CSV file into a DataFrame
# Load and clean data
def load_and_clean_data(path):
    df = pd.read_csv(path)
    df = df[df['Vis'].notnull()]
    return df


location1_data = load_and_clean_data('Era5_Stjohn.csv')
location2_data = load_and_clean_data('Era5_Yarmouth.csv')

# Ensure the time columns are in datetime format
location1_data['Time'] = pd.to_datetime(location1_data['Time'], format='%Y-%m-%d_%H:%M:%S')
location2_data['Time'] = pd.to_datetime(location2_data['Time'], format='%Y-%m-%d_%H:%M:%S')

# Add location identifiers
location1_data['Location'] = 'StJohn'
location2_data['Location'] = 'Yarmouth'

# Combine the datasets
combined_data = pd.concat([location1_data, location2_data])
combined_data.to_csv('combined_data.csv', index=False)

# One-hot encode the location column
combined_data = pd.get_dummies(combined_data, columns=['Location'], drop_first=False)

# Binary classification: Map 'class_vis' to binary classes (assuming 'clear' and 'fog' are the classes)
combined_data['class_vis'] = combined_data['class_vis'].map({'clear': 0, 'fog': 1})

# Extract time-based features
combined_data['Hour'] = combined_data['Time'].dt.hour
combined_data['Day'] = combined_data['Time'].dt.day
combined_data['Month'] = combined_data['Time'].dt.month
combined_data['DayOfWeek'] = combined_data['Time'].dt.dayofweek

#Sort the data by time
combined_data = combined_data.sort_values(by='Time')
combined_data = combined_data[combined_data['Month'] > 3]

# Drop the original time column
combined_data = combined_data.drop(['Time'], axis=1)

# Create lag features
lag_features = [col for col in combined_data.columns if col not in ['class_vis','T2-TD2','TD2','Vis','Hour','Day','Month','DayOfWeek','Location_StJohn','Location_Yarmouth']]
for feature in lag_features:
    for lag in range(1, 2):  # Creating lag features for the past 2 time steps
        combined_data[f'{feature}_lag_{lag}'] = combined_data[feature].shift(lag)

# Drop rows with missing values created by lag features
combined_data = combined_data.dropna()
# Preserve the locations data
location_columns = combined_data[['Location_StJohn', 'Location_Yarmouth']]

# Define features and target
X = combined_data.drop(['class_vis','Vis', 'T2-TD2','TD2'], axis=1)
y = combined_data['class_vis']

# Train-test split based on time
train_size = int(len(combined_data) * 0.9)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# Split the locations into train and test sets
locations_train = location_columns[:train_size]
locations_test = location_columns[train_size:]

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Apply SMOTE for data balancing
smote = BorderlineSMOTE()
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)

# @title Find the parameters

# Define the parameter distribution for RandomizedSearchCV
param_dist = {
    'n_estimators': randint(100, 500),
    'criterion': ['gini', 'log_loss', 'entropy'],
    'max_features': ['sqrt', 'log2',None],
    'max_depth': [10, 20, 30, 40, None],
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 5),
    'class_weight': ['balanced', 'balanced_subsample'],
    'bootstrap': [True, False]
}

# Initialize the Extra Trees classifier
et_classifier = ExtraTreesClassifier()

# Initialize RandomizedSearchCV
tscv = TimeSeriesSplit(n_splits=5)
random_search = RandomizedSearchCV(estimator=et_classifier, param_distributions=param_dist, scoring= make_scorer(f1_score, average='weighted'), n_iter=50, cv=tscv, n_jobs=-1, verbose=2)

# Fit the model
random_search.fit(X_train_res, y_train_res)

# Print the best parameters
print("Best Parameters:", random_search.best_params_)

# @title Building the Model
# Initialize and train ExtraTreeClassifier
et_classifier = ExtraTreesClassifier(
    n_estimators=475,  # Number of trees
    criterion = 'entropy',
    max_depth=40,      # Maximum depth of each tree
    max_features='log2',  # Number of features to consider when looking for the best split
    min_samples_split=5,  # Minimum number of samples required to split an internal node
    min_samples_leaf=3,   # Minimum number of samples required to be at a leaf node
    bootstrap= False,    # Whether bootstrap samples are used when building trees
    class_weight='balanced'
)
# Fit the model
et_classifier.fit(X_train_res, y_train_res)

# Predictions
y_train_pred = et_classifier.predict(X_train_scaled)
y_test_prob = et_classifier.predict_proba(X_test_scaled)
y_test_pred = (y_test_prob[:, 1] >= 0.6).astype(int)

# Evaluation on Training Set
train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred, average='weighted')
train_recall = recall_score(y_train, y_train_pred, average='weighted')
train_f1 = f1_score(y_train, y_train_pred, average='weighted')

print(f"Training Set Evaluation:\nAccuracy: {train_accuracy:.4f}")
print(f"Precision: {train_precision:.4f}")
print(f"Recall: {train_recall:.4f}")
print(f"F1-Score: {train_f1:.4f}")

# Evaluation on Test Set
test_accuracy = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred, average='weighted')
test_recall = recall_score(y_test, y_test_pred, average='weighted')
test_f1 = f1_score(y_test, y_test_pred, average='weighted')

print(f"Test Set Evaluation:\nAccuracy: {test_accuracy:.4f}")
print(f"Precision: {test_precision:.4f}")
print(f"Recall: {test_recall:.4f}")
print(f"F1-Score: {test_f1:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_test_pred))

# Cross-Validation
cv_scores = cross_val_score(et_classifier, X, y, cv=5)
print(f"Cross-Validation Scores: {cv_scores}")
print(f"Mean CV Accuracy: {cv_scores.mean():.4f}")

# Feature Importance
importances = et_classifier.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame(importances, index=feature_names, columns=['Importance']).sort_values('Importance', ascending=False)
print("\nFeature Importance:\n", feature_importance_df)

# Visualization of Feature Importance
plt.figure(figsize=(10, 6))
sns.barplot(x=feature_importance_df['Importance'], y=feature_importance_df.index)
plt.title('Feature Importance')
plt.show()

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_test_pred)
plt.figure(figsize=(10, 7))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
plt.title('Confusion Matrix for St Johns and Yarmouth combined')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# @title Evaluate the Perfomance
# Create a DataFrame with the scaled features and predicted values
X_test_df = pd.DataFrame(X_test_scaled, columns=X_train.columns)
X_test_df = X_test_df.reset_index(drop=True)  # Reset index for X_test_df
test_results = X_test_df.copy()
test_results['True'] = y_test.reset_index(drop=True)
test_results['Predicted'] = y_test_pred

# One-hot encode the location column
location_columns = ['Location_StJohn', 'Location_Yarmouth']

# Ensure test_results includes location columns from the original test set
test_results[location_columns] = X_test[location_columns].reset_index(drop=True)

# Group by locations and print the accuracy for each location
for location_col in location_columns:
    location_accuracy = test_results[test_results[location_col] == 1].apply(lambda x: x['True'] == x['Predicted'], axis=1).mean()
    location_name = location_col.split('_')[1]
    print(f"Accuracy for {location_name}: {location_accuracy:.4f}")

# Create classification reports for each location
for location_col in location_columns:
    location_name = location_col.split('_')[1]
    location_test_results = test_results[test_results[location_col] == 1]
    print(f"\nClassification Report for {location_name}:\n")
    print(classification_report(location_test_results['True'], location_test_results['Predicted']))

# Create confusion matrices for each location
for location_col in location_columns:
    location_name = location_col.split('_')[1]
    location_test_results = test_results[test_results[location_col] == 1]
    location_conf_matrix = confusion_matrix(location_test_results['True'], location_test_results['Predicted'])

    plt.figure(figsize=(10, 7))
    sns.heatmap(location_conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['clear', 'fog'], yticklabels=['clear', 'fog'])
    plt.title(f'Confusion Matrix for {location_name}  (Combined locations)')
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.show()

"""## Multi-Class"""

# @title Cleaning the Data
# Load the CSV file into a DataFrame
# Define the path and pattern for the CSV files
path = 'Era5multi_Stjohn.csv'

# Compute the Dask DataFrame to get a Pandas DataFrame
combined_df = pd.read_csv(path)
# Remove rows where the first column is blank
df_cleaned = combined_df[combined_df['Vis'].notnull()]

# Save the cleaned DataFrame back to a CSV file
df_cleaned.to_csv('cleaned_file.csv', index=False)

# @title Data Preparation
# Convert 'Time' column to datetime with the correct format
data = df_cleaned.copy()
data['Time'] = pd.to_datetime(data['Time'], format='%Y-%m-%d_%H:%M:%S', errors='coerce')

# Extract time-based features
data['Hour'] = data['Time'].dt.hour
data['Day'] = data['Time'].dt.day
data['Month'] = data['Time'].dt.month

# Sort the data by time
data = data.sort_values(by='Time')

data = data[data['Month'] > 3]
#data['Wind_Speed'] = (data['U']**2 + data['V']**2) ** 0.5

# Multi classification: Map 'class_vis' to multi classes
label_encoder = LabelEncoder()
data['class_vis'] = label_encoder.fit_transform(data['class_vis'])

# Create lag features
lag_features = ['T2','U','V','RH2','P_sfc', 'T2-TD2']  # feature names
for feature in lag_features:
    for lag in range(1, 2):  # Creating lag features for the past 2 time steps
        data[f'{feature}_lag_{lag}'] = data[feature].shift(lag)

# Drop rows with missing values created by lag features
data = data.dropna()

# Split data into features and target
X = data.drop(['Time', 'class_vis', 'Vis','TD2'], axis=1)  # Dropping 'Time' as it is now decomposed into useful features
y = data['class_vis']

# Train-test split based on time
train_size = int(len(data) * 0.9)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Apply SMOTE for data balancing
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import BorderlineSMOTE
smote= SMOTEENN()
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)
from imblearn.under_sampling import RandomUnderSampler
# Counting the labels
unique, counts = np.unique(y_train, return_counts=True)
print(dict(zip(unique, counts)))
# Define undersampling strategy
undersample = RandomUnderSampler(sampling_strategy={0: 10000, 1: 4259, 2: 2414}, random_state=42)

# Apply undersampling
#X_train_res, y_train_res = undersample.fit_resample(X_train, y_train)

# Check new class distribution
unique_resampled, counts_resampled = np.unique(y_train_res, return_counts=True)
print(dict(zip(unique_resampled, counts_resampled)))

# @title Find the parameters for St John

# Define the parameter distribution for RandomizedSearchCV
param_dist = {
    'n_estimators': randint(100, 500),
    'criterion': ['gini', 'log_loss', 'entropy'],
    'max_features': ['sqrt', 'log2', None],
    'max_depth': [10, 20, 30, 40, None],
    'min_samples_split': randint(2, 15),
    'min_samples_leaf': randint(1, 5),
    'class_weight': ['balanced', 'balanced_subsample', None],
    'bootstrap': [True, False]
}

# Initialize the Extra Trees classifier
et_classifier = ExtraTreesClassifier()

# Initialize RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=et_classifier, param_distributions=param_dist, scoring= f1_score, n_iter=50, cv=5, n_jobs=-1, verbose=2)

# Fit the model
random_search.fit(X_train_res, y_train_res)

# Print the best parameters
print("Best Parameters:", random_search.best_params_)

# @title Building the Model (St John)
# Initialize and train ExtraTreeClassifier
et_classifier = ExtraTreesClassifier(
    n_estimators=300,   # Number of trees
    criterion = 'gini',
    max_depth= None,      # Maximum depth of each tree
    max_features='sqrt',  # Number of features to consider when looking for the best split
    min_samples_split=14,  # Minimum number of samples required to split an internal node
    min_samples_leaf=2,   # Minimum number of samples required to be at a leaf node
    bootstrap= True,    # Whether bootstrap samples are used when building trees
    class_weight= 'balanced_subsample',
    random_state=42
)
# Fit the model
et_classifier.fit(X_train_res, y_train_res)

# Predictions
y_train_pred = et_classifier.predict(X_train_scaled)
y_test_prob = et_classifier.predict_proba(X_test_scaled)
y_test_pred = (y_test_prob[:, 1] >= 0.5).astype(int)

# Evaluation on Training Set
train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred, average='weighted')
train_recall = recall_score(y_train, y_train_pred, average='weighted')
train_f1 = f1_score(y_train, y_train_pred, average='weighted')

print(f"Training Set Evaluation:\nAccuracy: {train_accuracy:.4f}")
print(f"Precision: {train_precision:.4f}")
print(f"Recall: {train_recall:.4f}")
print(f"F1-Score: {train_f1:.4f}")

# Evaluation on Test Set
test_accuracy = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred, average='weighted')
test_recall = recall_score(y_test, y_test_pred, average='weighted')
test_f1 = f1_score(y_test, y_test_pred, average='weighted')

print(f"Test Set Evaluation:\nAccuracy: {test_accuracy:.4f}")
print(f"Precision: {test_precision:.4f}")
print(f"Recall: {test_recall:.4f}")
print(f"F1-Score: {test_f1:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_test_pred))

# Cross-Validation
cv_scores = cross_val_score(et_classifier, X, y, cv=5)
print(f"Cross-Validation Scores: {cv_scores}")
print(f"Mean CV Accuracy: {cv_scores.mean():.4f}")

# Feature Importance
importances = et_classifier.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame(importances, index=feature_names, columns=['Importance']).sort_values('Importance', ascending=False)
print("\nFeature Importance:\n", feature_importance_df)

# Visualization of Feature Importance
plt.figure(figsize=(10, 6))
sns.barplot(x=feature_importance_df['Importance'], y=feature_importance_df.index)
plt.title('Feature Importance (Multi-class)')
plt.show()

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_test_pred)
plt.figure(figsize=(10, 7))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['clear', 'fog', 'mist'], yticklabels=['clear','fog','mist'])
plt.title('Confusion Matrix (Multi-class)')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

"""# Regression"""

# @title Cleaning the Data
# Load the CSV file into a DataFrame
# Define the path and pattern for the CSV files
path = 'Era5_Stjohn.csv'

# Compute the Dask DataFrame to get a Pandas DataFrame
combined_df = pd.read_csv(path)
# Remove rows where the first column is blank
df_cleaned = combined_df[combined_df['Vis'].notnull()]

# Save the cleaned DataFrame back to a CSV file
df_cleaned.to_csv('cleaned_file.csv', index=False)

# @title Preparing the data
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load the dataset
df = pd.read_csv("cleaned_file.csv")

# Convert Time column to datetime and extract features
df['Time'] = pd.to_datetime(df['Time'], format='%Y-%m-%d_%H:%M:%S', errors='coerce')
df['hour'] = df['Time'].dt.hour
df['dayofyear'] = df['Time'].dt.dayofyear
df['month'] = df['Time'].dt.month

#clipping the Vis values to 5 km
df['Vis'] = df['Vis'].clip(upper=10)
# Log transform the target variable Vis
df['Vis'] = np.log1p(df['Vis'])  # log(Vis + 1) to handle zero cases

# Create lagged features except for Vis
lag_features = ['T2', 'TD2', 'T2-TD2', 'U', 'V', 'RH2', 'P_sfc']
for feature in lag_features:
    df[f'{feature}_lag1'] = df[feature].shift(1)

df.dropna(inplace=True)  # Remove rows with NaN values from lagging

# Drop unnecessary columns
df_reg = df.drop(columns=["class_vis"])

# Split into train (2012-2022) and test (2023) sets
df_train = df_reg[df_reg['Time'].dt.year < 2023]
df_test = df_reg[df_reg['Time'].dt.year == 2023]

# Separate features and target
X_train = df_train.drop(columns=["Time", "Vis"])
y_train = df_train["Vis"]
X_test = df_test.drop(columns=["Time", "Vis"])
y_test = df_test["Vis"]

# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# @title Initialize Extra Trees Regressor
et_regressor = ExtraTreesRegressor(random_state=42)

# Define parameter grid for RandomizedSearchCV
param_dist = {
    'n_estimators': [350, 400, 450, 500],
    'criterion': ['squared_error', 'friedman_mse', 'poisson', 'mean_absolute_error'],
    'max_depth': [30, 40, 50, None],
    'min_samples_split': [2, 4, 5, 10],
    'min_samples_leaf': [2, 3, 4, 5],
    'max_features': ['sqrt', 'log2', None],
    'bootstrap': [True, False]

}

# Perform Randomized Search with TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits=5)
random_search = RandomizedSearchCV(estimator=et_regressor, param_distributions=param_dist,
                                   n_iter=20, scoring='r2', cv=tscv, n_jobs=-1, verbose=2, random_state=42)
random_search.fit(X_train, y_train)

# Best parameters
best_params = random_search.best_params_
print("Best Parameters:", best_params)

# @title Train the best model
# Train the best model with sample weights
log_fog_threshold = np.log1p(1.2)  # log(1 + x)
sample_weights = np.where(y_train < log_fog_threshold, 5, 1) # Higher weight for low visibility cases
best_et_regressor = ExtraTreesRegressor(
    n_estimators= 450,  # 450
    criterion= 'squared_error', # squared_error
    max_depth= 50,  # 50
    min_samples_split= 2, # 2
    min_samples_leaf= 3, # 3
    bootstrap= False, # False
    max_features= 'log2', #log2
    random_state=42)

best_et_regressor.fit(X_train, y_train, sample_weight= sample_weights)

# Make predictions
y_pred = best_et_regressor.predict(X_test)

# Looking at the results for ETRegressor
# Inverse log transform predictions
y_pred1 = np.expm1(y_pred)
y_test1 = np.expm1(y_test)

# Evaluate model performance
mae = mean_absolute_error(y_test1, y_pred1)
mse = mean_squared_error(y_test1, y_pred1)
r2 = r2_score(y_test1, y_pred1)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"R2 Score: {r2}")

# Plot first 24 hours of predictions vs actual
plt.figure(figsize=(10, 5))
plt.plot(df_test['Time'].iloc[4000:4072], y_test1.iloc[4000:4072], label='Actual', marker='o')
plt.plot(df_test['Time'].iloc[4000:4072], y_pred1[4000:4072], label='Predicted', marker='x')

# Add a horizontal red line at y = 1.2 km to indicate fog threshold
plt.axhline(y=1.2, color='r', linestyle='--', label='Fog Threshold (1.2 km)')

plt.xlabel('Time')
plt.ylabel('Visibility')
plt.title('72 Hours: Predicted vs Actual Visibility')
plt.legend()
plt.xticks(rotation=45)
plt.grid()
plt.show()

# @title Quantile Regression Forest
from sklearn.ensemble import RandomForestRegressor
# Initialize Quantile Regression Forest (RandomForestRegressor with quantile support)
qrf = RandomForestRegressor(random_state=42)

# Define parameter grid for RandomizedSearchCV
param_dist = {
    'n_estimators': [50, 100, 200, 300, 400],
    'max_depth': [None, 10, 20, 30, 50],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 4, 8]
}

# Perform Randomized Search with TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits=5)
random_search = RandomizedSearchCV(estimator=qrf, param_distributions=param_dist,
                                   n_iter=20, scoring='r2', cv=tscv, n_jobs=-1, verbose=2, random_state=42)
random_search.fit(X_train, y_train)

# Best parameters
best_params = random_search.best_params_
print("Best Parameters:", best_params)

# @title Quantile Regression Forest with Vis clipped at 10km
from sklearn.ensemble import RandomForestRegressor
# Initialize Quantile Regression Forest (RandomForestRegressor with quantile support)
qrf = RandomForestRegressor(random_state=42)

# Define parameter grid for RandomizedSearchCV
param_dist = {
    'n_estimators': [50, 100, 200, 300, 400],
    'max_depth': [None, 10, 20, 30, 50],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 4, 8]
}

# Perform Randomized Search with TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits=5)
random_search = RandomizedSearchCV(estimator=qrf, param_distributions=param_dist,
                                   n_iter=20, scoring='r2', cv=tscv, n_jobs=-1, verbose=2, random_state=42)
random_search.fit(X_train, y_train)

# Best parameters
best_params = random_search.best_params_
print("Best Parameters:", best_params)

# Train the best model
from sklearn.ensemble import RandomForestRegressor

best_qrf = RandomForestRegressor(
    n_estimators= 200,
    max_depth= None,
    min_samples_split= 10,
    min_samples_leaf= 8,
    random_state=42)

best_qrf.fit(X_train, y_train)

# Predict quantiles
def predict_quantiles(model, X, quantiles=[0.05, 0.5, 0.95]):
    preds = np.array([tree.predict(X) for tree in model.estimators_])
    return {q: np.percentile(preds, q*100, axis=0) for q in quantiles}

quantiles = predict_quantiles(best_qrf, X_test)

# Inverse log transform predictions
y_pred_median = np.expm1(quantiles[0.5])
y_test = np.expm1(y_test)

# Evaluate model performance
mae = mean_absolute_error(y_test, y_pred_median)
mse = mean_squared_error(y_test, y_pred_median)
r2 = r2_score(y_test, y_pred_median)
rmse = np.sqrt(mse)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"R2 Score: {r2}")
print(f"RMSE: {rmse}")

"""10 km clip:
1.   MAE: 1.1662956627340302
2.   MSE: 5.456176253968357
3.   R2 Score: 0.6081773926737035
4. RMSE: 2.335845939690449

2 km clip:
1. MAE: 0.1485630970389236
2. MSE: 0.11526540181271604
3. R2 Score: 0.6161231468563525
4. RMSE: 0.33950758726826125
"""

plt.figure(figsize=(10, 5))

# Actual Visibility
plt.plot(df_test['Time'].iloc[4000:4072], y_test.iloc[4000:4072], label='Actual', marker='o')

# Predicted Median Visibility
plt.plot(df_test['Time'].iloc[4000:4072], y_pred_median[4000:4072], label='Predicted Median', marker='x')

# 90% Prediction Interval (Shaded Region)
plt.fill_between(
    df_test['Time'].iloc[4000:4072],
    np.expm1(quantiles[0.05])[4000:4072],  # 5th percentile (lower bound)
    np.expm1(quantiles[0.95])[4000:4072],  # 95th percentile (upper bound)
    color='gray', alpha=0.3, label='90% Prediction Interval'
)
# Add a horizontal red line at y = 1.2 km to indicate fog threshold
plt.axhline(y=1.2, color='r', linestyle='--', label='Fog Threshold (1.2 km)')

plt.xlabel('Time/ UTC')
plt.ylabel('Visibility/ km')
plt.title('72 Hours: With Visibility clipped at 10 km (Quant. Regression)')
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.xticks(rotation=45)
plt.grid()
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))

# Actual Visibility
plt.plot(df_test['Time'].iloc[4000:4072], y_test.iloc[4000:4072], label='Actual', marker='o')

# Predicted Median Visibility
plt.plot(df_test['Time'].iloc[4000:4072], y_pred_median[4000:4072], label='Predicted Median', marker='x')

# 90% Prediction Interval (Shaded Region)
plt.fill_between(
    df_test['Time'].iloc[4000:4072],
    np.expm1(quantiles[0.05])[4000:4072],  # 5th percentile (lower bound)
    np.expm1(quantiles[0.95])[4000:4072],  # 95th percentile (upper bound)
    color='gray', alpha=0.3, label='90% Prediction Interval'
)
# Add a horizontal red line at y = 1.2 km to indicate fog threshold
plt.axhline(y=1.2, color='r', linestyle='--', label='Fog Threshold (1.2 km)')

plt.xlabel('Time/ UTC')
plt.ylabel('Visibility/ km')
plt.title('72 Hours: With Visibility clipped at 2 km (Quant. Regression)')
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.xticks(rotation=45)
plt.grid()
plt.tight_layout()
plt.show()